<?php
return array (
  'tkm3u8' => 
  array (
    'status' => '1',
    'from' => 'tkm3u8',
    'show' => '天空',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'https://vod.nqcode.cn/jiuqingplayer/?url=',
    'parse2' => '',
    'sort' => '9999',
    'tip' => '无需安装任何插件',
    'id' => 'tkm3u8',
  ),
  'dbm3u8' => 
  array (
    'status' => '1',
    'from' => 'dbm3u8',
    'show' => '百度',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'https://cdn.zyc888.top/?url=',
    'parse2' => '',
    'sort' => '9998',
    'tip' => '无需安装任何插件',
    'id' => 'dbm3u8',
  ),
  'kbm3u8' => 
  array (
    'status' => '1',
    'from' => 'kbm3u8',
    'show' => '快播',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'https://vod.nqcode.cn/jiuqingplayer/?url=',
    'parse2' => '',
    'sort' => '9997',
    'tip' => '无需安装任何插件',
    'id' => 'kbm3u8',
  ),
  'qiyi' => 
  array (
    'status' => '1',
    'from' => 'qiyi',
    'show' => '奇艺',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'https://vod.nqcode.cn/jiexi/?url=',
    'parse2' => 'https://vip..parwix.com:4433/analysis/json/?uid=641&my=chlnptwxDEFJKSW079&url=',
    'sort' => '1006',
    'tip' => '无需安装任何插件',
    'id' => 'qiyi',
  ),
  'qq' => 
  array (
    'status' => '1',
    'from' => 'qq',
    'show' => '腾讯',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'https://vod.nqcode.cn/jiexi/?url=',
    'parse2' => 'https://vip..parwix.com:4433/analysis/json/?uid=641&my=chlnptwxDEFJKSW079&url=',
    'sort' => '1005',
    'tip' => '无需安装任何插件',
    'id' => 'qq',
  ),
  'youku' => 
  array (
    'status' => '1',
    'from' => 'youku',
    'show' => '优酷',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'https://vod.nqcode.cn/jiexi/?url=',
    'parse2' => 'https://2..jiuqing.xyz/analysis/json/?uid=1&my=aefmnxzBDIPSVWY129&url=',
    'sort' => '1004',
    'tip' => '无需安装任何插件',
    'id' => 'youku',
  ),
  'sohu' => 
  array (
    'status' => '1',
    'from' => 'sohu',
    'show' => '搜狐',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'https://vod.nqcode.cn/jiexi/?url=',
    'parse2' => 'https://vip..parwix.com:4433/analysis/json/?uid=641&my=chlnptwxDEFJKSW079&url=',
    'sort' => '1003',
    'tip' => '无需安装任何插件',
    'id' => 'sohu',
  ),
  'mgtv' => 
  array (
    'status' => '1',
    'from' => 'mgtv',
    'show' => '芒果',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'https://vod.nqcode.cn/jiexi/?url=',
    'parse2' => 'https://vod.nqcode.cn/jiexi/?url=',
    'sort' => '1002',
    'tip' => '无需安装任何插件',
    'id' => 'mgtv',
  ),
  'pptv' => 
  array (
    'status' => '1',
    'from' => 'pptv',
    'show' => 'PPTV',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'https://vod.nqcode.cn/jiexi/?url=',
    'parse2' => 'https://vod.nqcode.cn/jiexi/?url=',
    'sort' => '1001',
    'tip' => '无需安装任何插件',
    'id' => 'pptv',
  ),
  'letv' => 
  array (
    'status' => '1',
    'from' => 'letv',
    'show' => '乐视',
    'des' => '支持手机电脑在线播放',
    'ps' => '1',
    'parse' => 'https://vod.nqcode.cn/jiexi/?url=',
    'parse2' => 'https://vod.nqcode.cn/jiexi/?url=',
    'sort' => '1000',
    'tip' => '无需安装任何插件',
    'id' => 'letv',
  ),
);